// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4b5feDovgs0rZ_MZzrLuk9QQnB-5Fnc',
    appId: '1:385358109408:web:84839b7bd07fd2e8444e85',
    messagingSenderId: '385358109408',
    projectId: 'charity-252d1',
    authDomain: 'charity-252d1.firebaseapp.com',
    storageBucket: 'charity-252d1.appspot.com',
    measurementId: 'G-P9Q3SMZ5CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATIGv7Y260Ty5Ob2uPcO926PpRwUK6F0E',
    appId: '1:385358109408:android:f6586a80d5dbdc6d444e85',
    messagingSenderId: '385358109408',
    projectId: 'charity-252d1',
    storageBucket: 'charity-252d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr9a2IRUgCW3N5Y7sFZlmJo4vbzOYRA9k',
    appId: '1:385358109408:ios:d36e6e86d2e84201444e85',
    messagingSenderId: '385358109408',
    projectId: 'charity-252d1',
    storageBucket: 'charity-252d1.appspot.com',
    iosClientId: '385358109408-mvbh4m0mr802jpaq0t1nna3f4us7t029.apps.googleusercontent.com',
    iosBundleId: 'com.example.charityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr9a2IRUgCW3N5Y7sFZlmJo4vbzOYRA9k',
    appId: '1:385358109408:ios:d36e6e86d2e84201444e85',
    messagingSenderId: '385358109408',
    projectId: 'charity-252d1',
    storageBucket: 'charity-252d1.appspot.com',
    iosClientId: '385358109408-mvbh4m0mr802jpaq0t1nna3f4us7t029.apps.googleusercontent.com',
    iosBundleId: 'com.example.charityApp',
  );
}
