// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKqbkrlAJXtXxbdh37CGJJ8-rXBRCQmb4',
    appId: '1:846923342543:web:c942c3f7fc1b3524fd8dba',
    messagingSenderId: '846923342543',
    projectId: 'charity-sharing-app',
    authDomain: 'charity-sharing-app.firebaseapp.com',
    storageBucket: 'charity-sharing-app.appspot.com',
    measurementId: 'G-6G2Y5HPD4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAauEzLgElZvzmJE_t3LRDLeAMmro_kDS8',
    appId: '1:846923342543:android:413d8209d4cb9fa5fd8dba',
    messagingSenderId: '846923342543',
    projectId: 'charity-sharing-app',
    storageBucket: 'charity-sharing-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_mjpjojPvZPnTwq8R0UkyF56-bLVGeAA',
    appId: '1:846923342543:ios:f9fedded717ee899fd8dba',
    messagingSenderId: '846923342543',
    projectId: 'charity-sharing-app',
    storageBucket: 'charity-sharing-app.appspot.com',
    iosClientId: '846923342543-mckg71b75dlompodni3dlpg0mme8gcct.apps.googleusercontent.com',
    iosBundleId: 'com.example.charity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_mjpjojPvZPnTwq8R0UkyF56-bLVGeAA',
    appId: '1:846923342543:ios:f9fedded717ee899fd8dba',
    messagingSenderId: '846923342543',
    projectId: 'charity-sharing-app',
    storageBucket: 'charity-sharing-app.appspot.com',
    iosClientId: '846923342543-mckg71b75dlompodni3dlpg0mme8gcct.apps.googleusercontent.com',
    iosBundleId: 'com.example.charity',
  );
}
